export const TOGGLE_TYPE_LAYOUT_VIEW = '@@TOGGLE_TYPE_LAYOUT_VIEW/options';
export const CHANGE_TYPE_SPACE_VIEW = '@@CHANGE_TYPE_SPACE_VIEW/options';
export const CHANGE_TYPE_PREFERENCES = '@@CHANGE_TYPE_PREFERENCES/options';
