export const GET_LIST_QUIZZ = '@@GET_LIST_QUIZZ/quizz';
export const GET_LIST_QUIZZ_SUCCESS = '@@GET_LIST_QUIZZ_SUCCESS/quizz';
export const GET_LIST_QUIZZ_FAIL = '@@GET_LIST_QUIZZ_FAIL/quizz';

export const GET_LIST_QUIZZ_SCROLL = '@@GET_LIST_QUIZZ_SCROLL/quizz';
export const GET_LIST_QUIZZ_SCROLL_SUCCESS =
  '@@GET_LIST_QUIZZ_SCROLL_SUCCESS/quizz';
